server:
  port: 8081

spring:
  datasource:
    url: ${JDBC_URL:jdbc:mysql://localhost:3306/yc?useUnicode=true&characterEncoding=utf8}
    username: ${DB_USER:imp}
    password: ${DA_PASS:root123}
    driver-class-name: com.mysql.jdbc.Driver